attributes:
  metadata:
    restrictions:
      - condition: cluster:net_provider != 'neutron'
        action: hide
  mem:
    value: false
    label: "Midokura Enterprise MidoNet (MEM)"
    description: "If selected, Midokura Enterprise MidoNet (MEM) will be installed."
    weight: 6
    type: "checkbox"

  mem_version:
    value: "v1.9"
    label: "MEM release version"
    description: "Choose the Midokura Enterprise MidoNet (MEM) release version"
    type: "select"
    weight: 7
    values:
      - data: "v1.9"
        label: "v1.9"
    restrictions:
      - condition: "settings:midonet-fuel-plugin.mem.value == false"
        strict: false
        message: "Midokura Enterprise MidoNet (MEM) must be enabled"

  mem_repo_user:
    value: ''
    label: "MEM repository username"
    description: "Username for Midokura Enterprise MidoNet (MEM) repository"
    type: "text"
    weight: 8
    restrictions:
      - condition: "settings:midonet-fuel-plugin.mem.value == false"
        strict: false
        message: "Midokura Enterprise MidoNet (MEM) must be enabled"

  mem_repo_password:
    value: ''
    label: "MEM repository password"
    description: "Password for Midokura Enterprise MidoNet (MEM) repository"
    type: "text"
    weight: 9
    restrictions:
      - condition: "settings:midonet-fuel-plugin.mem.value == false"
        strict: false
        message: "Midokura Enterprise MidoNet (MEM) must be enabled"

  tunnel_type:
    type: "select"
    weight: 10
    value: "gre"
    label: "Tunnel Type"
    description: "Choose which technology MidoNet will use to encapsulate data between hosts"
    values:
      - data: "gre"
        label: "GRE tunnels"
      - data: "vxlan"
        label: "VXLAN tunnels"
    restrictions:
      - condition: "settings:public_network_assignment.assign_to_all_nodes == false"
        action: "hide"

  # Floating IP range #
  floating_cidr:
    value: '200.200.200.0/24'
    label: 'Floating Network subnet'
    description: 'CIDR of the Floating Network. Will override the default settings'
    weight: 20
    type: "text"
    regex:
      source: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])/(3[012]|[12]?[0-9])$'
      error: 'Floating Network must be a CIDR'

  gateway:
    value: '200.200.200.1'
    label: 'Floating Network Gateway IP'
    description: 'Gateway of the Floating Network. Will override the default settings'
    weight: 21
    type: "text"
    regex:
      source: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$'
      error: 'Floating Network gateway must be an IP address'

  floating_ip_range_start:
    value: '200.200.200.100'
    label: 'Floating Network range start'
    description: 'First IP address of the Floating Network range. Will override the default settings'
    weight: 22
    type: "text"
    regex:
      source: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$'
      error: 'Floating Network range start value must be an IP address'

  floating_ip_range_end:
    value: '200.200.200.200'
    label: 'Floating Network range end'
    description: 'Last IP address of the Floating Network range. Will override the default settings'
    weight: 23
    type: "text"
    regex:
      source: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$'
      error: 'Floating Network range last value must be an IP address'

  ## BGP Options ###
  bgp_cidr:
    value: '10.88.88.0/30'
    label: 'BGP routing subnet'
    description: 'CIDR of the BGP network'
    weight: 30
    type: "text"
    regex:
      source: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])/(3[012]|[12]?[0-9])$'
      error: 'BGP Network must be a CIDR'

  bgp_ip:
    value: '10.88.88.2'
    label: 'BGP local IP address'
    description: 'IP address of the first Local BGP peer'
    weight: 31
    type: "text"
    regex:
      source: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$'
      error: 'Local BGP peer must be an IP address'

  local_as:
    value: '12345'
    label: 'BGP local AS'
    description: 'Autonomous System Number of the MidoNet Gateway'
    weight: 32
    type: "text"
    regex:
      source: '^([0-9]){5}$'
      error: "BGP local AS must be an integer of 5 digits"

  remote_ip1:
    value: '10.88.88.1'
    label: 'BGP peer IP address'
    description: 'IP address of the BGP peer'
    weight: 33
    type: "text"
    regex:
      source: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$'
      error: 'Remote BGP peer must be an IP address'

  remote_as1:
    value: '65535'
    label: 'BGP peer AS'
    description: 'Autonomous System Number of the BGP peer'
    weight: 34
    type: "text"
    regex:
      source: '^([0-9]){5}$'
      error: "Remote AS must be an integer of 5 digits"
